; PlatformIO Project Configuration File
; Project: WT32-eth01-mbus-tcp2mqtt
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = wt32-eth01-dev

[env]
platform = espressif32
board = wt32-eth01
framework = arduino
board_build.partitions = partitions.csv
lib_deps = 
	knolleary/PubSubClient@^2.8	
	bblanchon/ArduinoJson@^7.0.4
monitor_speed = 115200

[env:wt32-eth01-dev]
extends = env
build_flags = 
	-DRECOVERY_MODE_DEV_UART=1
	-DRECOVERY_MODE_PROD_GPIO=0


[env:wt32-eth01-prod]
extends = env
build_flags = 
	-DRECOVERY_MODE_DEV_UART=0
	-DRECOVERY_MODE_PROD_GPIO=1